name: csslib
version: 1.0.0
author: Dart Team <misc@dartlang.org>
description: A library for parsing CSS.
homepage: https://github.com/dart-lang/csslib
environment:
  sdk: ^1.0.0
dependencies:
  charcode: any
  source_span: any
dev_dependencies:
  test: any
